apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: dev
spec:
  encryptedData:
    password: AgByrqZDbDSFNE9J90xutbYj1IyPtnzSk7Magez8odHJlb/VhIWkGd3SnOdXUuStbZMQ6k7UPJcChzrQDetahzOMlvmKheXPLykKT4oRpkiDxZ5tMyzX2z1iHMf6jwjnM0yOTt2BJyQDNOSXTNdj/JTri3ot9zwrDYpcEP1I7jsHnomG8UOfswKKxRj0AJve4V3X7abNX2X/qvuJsm0m+0oJU7l07ePniLX2taRxbYHl/6VYqkQaSUkDkWfBdbUS8iI+JHxMw7V2sQX9SmV1jW3qdK1fET6b1Xkn//kULHtXHU2FqI6kcDvmXgly8qbrX6Kkb7aBkHUBCgX6mpXrvtMtxRmLiSGeUIEwIRwtr64iC3ClF/VeZWwANxrukXhS/gyXV7qjb2C8kc+lmdxbbmq6fNPM1c1MYM3GBL8UVKyJQqkULtaARFB2/vdwqiDqLBL59xcrUsNH2QydzYL0b2ZhOJgDdqzOeBh8zb6I7rbp2QgUI8OaBWgEVg+zdpDB7ToS0KLtVC95n7TrH2C6SA8AuUsQrFa13mqsTNHSpYADPBjTTkqMCIU+PsYAFfOb5cWG4SvFb6EHHV5XhiKLiYDZ5h4ccGCJ4DpgXCA57PkiStpQuWmDbJbZGrGkSTBuIxbJHstJGXtTgwpuud95uKZqGKvdvtQjz6JyMcBVRf0w9qBvVgTSCfk4oo0Catm6PeOCQgWUXg==
    user: AgCIegsnMDiczyFx7z/3HpCE9WqGReonN8bj5MqDKz4aGFD2zquSxlVct3VvkIS78BbSevWVcETc6A5bC2VqaSXY7l+kR5HFJhwPu83VCFnniuuJ51+raSimetPv4yuXf22OmxFXpqMXPEvy7l4nYp9pvsK2S1jxzw3fsp3sMIHTwgHSOjcv1QIyjz6ylD81dFz4RYcgu+VqNG2WY7kGUw2ajVFe5JzUlAiVMwzui7c6Dc1L9/V//In+sYkuqb716Q6WW0fyyCp1/jkXntTOt1zq15JilEahkSEXCuITao5qwZcMSo68t/L3G7iz5OAWp3DxFqcJjpKHvFX4znRXT9qFDph2X0gOBMRVP+jSWNk1GL5oPyVnZKWcRJj/ChD2tO893azLKl7Zx5ZZg85Okm0pC1mttVvJ69pd2Dtry6ulzuBH/yxVCe9+j3X8ImwcASHrp1gcB37FzxPi32jfoqs+rlRUQHPCIXcvDmWrCYKTaUA3I5DYHuXCJGcPFjO/vh3ZzjQVYGN3tNQj51R6R7nIye/w1bYtKKzm3Y8DvifrNDHvx1ic/7GeLDCUlTITezJx+gY+XfK0N7uLUDRH3jPtIvaVupEaHkJUQlXaJQ3NYYrZfxVUtcyBvQQ3jyaIIfmPq/p0OfUItg2YFNNqyoZdytDr6MY8JRsumSDxbZM1kiDgnHZpZWx1vseLe5IAfiup/LcMzA==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: dev
status: {}

